version: 2.1

jobs:
  test_and_build:
    parameters:
      toolchain:
        type: string
        default: stable
      run_lint:
        type: boolean
        default: true
      run_fmt:
        type: boolean
        default: true
    docker:
      - image: cimg/rust:<< parameters.toolchain >>
    steps:
      - checkout
      - when:
          condition: << parameters.run_fmt >>
          steps:
            - run: rustup component add rustfmt
            - run: cargo fmt
      - when:
          condition: << parameters.run_lint >>
          steps:
            - run: rustup component add clippy
            - run: cargo clippy
      - run:
          name: test
          command: cargo test --all --release
      - run:
          name: build
          command: cargo build --release
      - persist_to_workspace:
          root: ~/project
          paths:
            - "target/release/release-with-bin"
    
  upload_artifact:
    docker:
      - image: cimg/go:1.17
    steps:
      - attach_workspace:
          at: "~/project"
      - run:
          name: "pack artifacts"
          command: |
            mkdir -p ./artifacts
            tar -zcvf artifacts/release-with-bin.tar.gz target/release/release-with-bin 
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_PKG_TOKEN} -u ${GITHUB_USR} -r release-with-bin -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./artifacts


workflows:
  test_and_build:
    jobs:
      - test_and_build:
          toolchain: 1.58.1
          filters:
            tags:
              only: /^v.*/

      - upload_artifact:
          requires:
            - test_and_build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
